apiVersion: v1
kind: Service

metadata:
  name: thetagless-service

spec:
  selector:
    app: thetagless

  type: NodePort

  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080